### PR TITLE
add span links from SQS messages in AWS lambda transactions

### LINKED ISSUE #1473: [META 605] Add span links for message tracing
Meta issue:
- https://github.com/elastic/apm/issues/605

Summary of spec changes:

- If your agent instruments any of Azure Service Bus, JMS, Kafka, RabbitMQ, SQS, or SNS, then instrumentation for receiving messages or batches of messages "SHOULD":
    - Create a transaction (with trace-context from message metadata, if any) for the handling of each message, if possible.
    - Otherwise, when creating the transaction or span for the message or batch of messages, look for trace-context in metadata for up to 1000 messages and create a span link for each.
- If your agent supports AWS Lambda instrumentation, then in addition to the creation of span links, this spec change has a number of changes to the context captured for SQS and SNS-triggered invocations. (The special-casing of a message batch with a single message has been dropped.)

### PR DESCRIPTION
**Pull request by beniwohli**
closes #1473

### CODE REVIEW

**Comment by beniwohli** [comment]
@basepi do you have a real word setup already where we could test this in AWS?

**Comment by basepi** [comment]
> @basepi do you have a real word setup already where we could test this in AWS?

I have a working setup on the receiving end, but not on the sending end. I can probably do something later this week, couple of higher priority things at the moment.

**Comment by trentm** [comment]
If it helps, here is an SQS payload that we use for Node.js agent tests: https://github.com/elastic/apm-agent-nodejs/blob/main/test/lambda/fixtures/aws_sqs_test_data.json#L26-L37

It *started* as a real payload... to which I manually added the *two* conflicting Traceparent message attributes for testing.

**Comment by trentm** [comment]
And if it helps, here are some AWS CLI commands I used to send SQS messages:

```
aws sqs create-queue --queue-name trentm-play-queue1
{
    "QueueUrl": "https://sqs.us-west-2.amazonaws.com/627286350134/trentm-play-queue"
}

aws sqs send-message \
    --queue-url "https://sqs.us-west-2.amazonaws.com/627286350134/trentm-play-queue" \
    --message-body 'this is my body' \
    --message-attributes '{
        "astr": {"DataType": "String", "StringValue": "a str value"}
    }'

aws sqs send-message \
    --queue-url "https://sqs.us-west-2.amazonaws.com/627286350134/trentm-play-queue" \
    --message-body 'this is my body' \
    --message-attributes file://send-message.json


       Command:

          aws sqs send-message --queue-url https://sqs.us-east-1.amazonaws.com/80398EXAMPLE/MyQu
eue --message-body "Information about the largest city in Any Region." --delay-seconds 10 --mess
age-attributes file://send-message.json

       Input file (send-message.json):

          {
            "City": {
              "DataType": "String",
              "StringValue": "Any City"
            },
            "Greeting": {
              "DataType": "Binary",
              "BinaryValue": "Hello, World!"
            },
            "Population": {
              "DataType": "Number",
              "StringValue": "1250800"
            }
          }

       Output:

          {
            "MD5OfMessageBody": "51b0a325...39163aa0",
            "MD5OfMessageAttributes": "00484c68...59e48f06",
            "MessageId": "da68f62c-0c07-4bee-bf5f-7e856EXAMPLE"
          }
```

**Review by basepi — APPROVED** [review]
Works beautifully! I see the incoming span link on my boto3 transaction to send the sqs message, and the outgoing span link on the lambda function transaction:

image

image

**Pull request merged**
