### PR TITLE
Add instrumentation for httpx

### LINKED ISSUE #739: [Feature] encode/httpx support
A friend and I were chatting recently about async libraries in python. He had nothing but good things to say about the tools in https://github.com/encode

`httpx` seems like a no-brainer, in particular: https://github.com/encode/httpx

### PR DESCRIPTION
**Pull request by HenrikOssipoff**
## What does this pull request do?
Adds instrumentation for `httpx.Client` and `httpx.AsyncClient`.

Inspiration taken from the `requests` instrumentation, as the interface is more or less the same.

**TODO**
- [ ] Add tests
- [x] Add PR link in Changelog

## Related issues
closes #739

### CODE REVIEW

**Comment by basepi** [comment]
This looks excellent so far! Once you add those tests we'll get it merged!

**Comment by basepi** [comment]
jenkins run the tests please

**Comment by HenrikOssipoff** [comment]
Sorry about the slow pace here, will add tests during the weekend.

**Comment by basepi** [comment]
No hurry! We're very happy to be patient on community contributions. :)

**Comment by HenrikOssipoff** [comment]
@basepi Hi, so this took way longer than it should for me to get back.
I've spent the better part of an hour looking through the test suite just now, and I must admit, that I simply don't understand how it works well enough for me to be confident in writing any tests that are fully covering.
It might be that I'm not familiar enough with pytest specifically. I'm also not sure how to run the tests locally, even after having read through the documentation.
While it annoys me to say this, I think I won't be able to complete this PR for these reasons unfortunately, so someone else can probably take over.

I'll dedicate some time at some point to getting to know the test setup, since I have a lot of things I'd potentially want to contribute to this project, but without being able to do the test part, I don't feel confident enough in doing so.

Very sorry!

**Comment by basepi** [comment]
Thanks @HenrikOssipoff, I can take over from here. 

I guess we need a little better documentation around the tests, but here's a super-quick rundown:

* Install relevant requirements from from [tests/requirements](https://github.com/elastic/apm-agent-python/tree/master/tests/requirements) (reqs-base.txt at the very least)
* Run `py.test` in the project root directory

Honestly it should be that simple. The most confusing thing about writing tests in pytest is [fixtures](https://docs.pytest.org/en/stable/fixture.html), mostly because they don't need to be imported, and as such are difficult to discover. For example, any time a test has `elasticapm_client` as an argument, that's actually a fixture, which you can find [here](https://github.com/elastic/apm-agent-python/blob/ed4ce5fd5db3cc091a54d3328384fbce62635bbb/tests/fixtures.py#L150).

Hopefully that helps for your future contributions!

**Comment by basepi** [comment]
Closing as #898 will be used to finish this up.

**Pull request closed without merging**
