### PR TITLE
be a bit more careful with decoding the APM Server get_config response to JSON

### PR DESCRIPTION
**Pull request by beniwohli**
apparently, there are still cases where the answer could be invalid JSON,
see https://github.com/elastic/apm-agent-python/issues/562#issuecomment-730612349

### CODE REVIEW

**Comment by JBauto** [comment]
Here is the output. FastAPI gets requests from a Vue frontend (also with ElasticAPM).

Failed decoding APM Server response as JSON: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><title>frontend</title><link href="/css/chunk-004556ab.793d1bc3.css" rel="prefetch"><link href="/css/chunk-02b4ca8f.777e364d.css" rel="prefetch"><link href="/css/chunk-09278fb6.777e364d.css" rel="prefetch"><link href="/css/chunk-0c0a898e.88947eaf.css" rel="prefetch"><link href="/css/chunk-1540d222.846e552f.css" rel="prefetch"><link href="/css/chunk-17129a44.bd3992c0.css" rel="prefetch"><link href="/css/chunk-1a27a25e.c9266459.css" rel="prefetch"><link href="/css/chunk-1b901888.986c9aec.css" rel="prefetch"><link href="/css/chunk-21f75a54.78b4b34d.css" rel="prefetch"><link href="/css/chunk-22a95ec4.f4cf68b8.css" rel="prefetch"><link href="/css/chunk-253f85d3.56f34a97.css" rel="prefetch"><link href="/css/chunk-2d409712.777e364d.css" rel="prefetch"><link href="/css/chunk-3295a463.ca98f90d.css" rel="prefetch"><link href="/css/chunk-39f60ac8.4681fd26.css" rel="prefetch"><link href="/css/chunk-3c5e37f6.d0ebfeb5.css" rel="prefetch"><link href="/css/chunk-3ffa8aee.abe2ccc3.css" rel="prefetch"><link href="/css/chunk-401304c8.b2194a9e.css" rel="prefetch"><link href="/css/chunk-4300c5fe.03961584.css" rel="prefetch"><link href="/css/chunk-554af635.ed59eb1a.css" rel="prefetch"><link href="/css/chunk-5d057598.1ea628b0.css" rel="prefetch"><link href="/css/chunk-5f5e0048.47ac33f0.css" rel="prefetch"><link href="/css/chunk-6099a2de.9a23af9b.css" rel="prefetch"><link href="/css/chunk-61a276a8.ba280342.css" rel="prefetch"><link href="/css/chunk-656eb496.3ca51ed6.css" rel="prefetch"><link href="/css/chunk-72a78490.96f71326.css" rel="prefetch"><link href="/css/chunk-73effd7d.ccd95a9e.css" rel="prefetch"><link href="/css/chunk-78ec4fe4.777e364d.css" rel="prefetch"><link href="/css/chunk-8867368c.3dffaad2.css" rel="prefetch"><link href="/css/chunk-94ed7ad8.70a8ec03.css" rel="prefetch"><link href="/css/chunk-9663e300.533fabeb.css" rel="prefetch"><link href="/css/chunk-978b8618.08955cee.css" rel="prefetch"><link href="/css/chunk-9a85b5c6.846e552f.css" rel="prefetch"><link href="/css/chunk-ac292d6c.598aea96.css" rel="prefetch"><link href="/css/chunk-ad258162.4e0d5a8a.css" rel="prefetch"><link href="/css/chunk-e0db6f82.6940beaa.css" rel="prefetch"><link href="/css/chunk-ec92e0f2.71d7e085.css" rel="prefetch"><link href="/css/chunk-f9cfcd9a.228448df.css" rel="prefetch"><link href="/css/chunk-fc4354c6.86179ace.css" rel="prefetch"><link href="/js/chunk-004556ab.cabbd308.js" rel="prefetch"><link href="/js/chunk-02b4ca8f.ea6fcc09.js" rel="prefetch"><link href="/js/chunk-03b1eae6.0202c921.js" rel="prefetch"><link href="/js/chunk-09278fb6.59329a58.js" rel="prefetch"><link href="/js/chunk-0c0a898e.a763e604.js" rel="prefetch"><link href="/js/chunk-1540d222.c1bf3346.js" rel="prefetch"><link href="/js/chunk-17129a44.af2863a0.js" rel="prefetch"><link href="/js/chunk-1a27a25e.df09d11e.js" rel="prefetch"><link href="/js/chunk-1ab431d2.b43d6a91.js" rel="prefetch"><link href="/js/chunk-1b901888.5005d25f.js" rel="prefetch"><link href="/js/chunk-21f75a54.13de6170.js" rel="prefetch"><link href="/js/chunk-22a95ec4.764e8a59.js" rel="prefetch"><link href="/js/chunk-253f85d3.446fda6f.js" rel="prefetch"><link href="/js/chunk-2d0a443c.a7c201cb.js" rel="prefetch"><link href="/js/chunk-2d0e4494.b4f7bb3c.js" rel="prefetch"><link href="/js/chunk-2d21d120.8b5cc107.js" rel="prefetch"><link href="/js/chunk-2d409712.3f6410d8.js" rel="prefetch"><link href="/js/chunk-3295a463.c4b05852.js" rel="prefetch"><link href="/js/chunk-39f60ac8.5c4ca02b.js" rel="prefetch"><link href="/js/chunk-3c5e37f6.7df04ce4.js" rel="prefetch"><link href="/js/chunk-3ffa8aee.ca3dec6c.js" rel="prefetch"><link href="/js/chunk-401304c8.48300ce5.js" rel="prefetch"><link href="/js/chunk-4300c5fe.08ce00b8.js" rel="prefetch"><link href="/js/chunk-514d86d8.c1298a42.js" rel="prefetch"><link href="/js/chunk-554af635.0d8b7d83.js" rel="prefetch"><link href="/js/chunk-5d057598.e5751b34.js" rel="prefetch"><link href="/js/chunk-5f5e0048.1b772b9d.js" rel="prefetch"><link href="/js/chunk-6099a2de.c01f06f1.js" rel="prefetch"><link href="/js/chunk-61a276a8.8ba4ba7e.js" rel="prefetch"><link href="/js/chunk-656eb496.2d695292.js" rel="prefetch"><link href="/js/chunk-6e979c7a.dadbecb7.js" rel="prefetch"><link href="/js/chunk-72a78490.bebf1bf3.js" rel="prefetch"><link href="/js/chunk-73effd7d.2bcabd02.js" rel="prefetch"><link href="/js/chunk-78ec4fe4.c566d709.js" rel="prefetch"><link href="/js/chunk-8867368c.03a2cd13.js" rel="prefetch"><link href="/js/chunk-94ed7ad8.e1f789ab.js" rel="prefetch"><link href="/js/chunk-9663e300.83c79610.js" rel="prefetch"><link href="/js/chunk-978b8618.9d7aa20c.js" rel="prefetch"><link href="/js/chunk-9a85b5c6.a7a17f12.js" rel="prefetch"><link href="/js/chunk-ac292d6c.f444a78c.js" rel="prefetch"><link href="/js/chunk-ad258162.0e701395.js" rel="prefetch"><link href="/js/chunk-e0db6f82.f071d746.js" rel="prefetch"><link href="/js/chunk-ec92e0f2.c7526ac4.js" rel="prefetch"><link href="/js/chunk-f9cfcd9a.8785082b.js" rel="prefetch"><link href="/js/chunk-fc4354c6.9ba45a94.js" rel="prefetch"><link href="/css/app.b302f5be.css" rel="preload" as="style"><link href="/css/chunk-vendors.ce44b678.css" rel="preload" as="style"><link href="/js/app.b36ccd51.js" rel="preload" as="script"><link href="/js/chunk-vendors.a9b269ce.js" rel="preload" as="script"><link href="/css/chunk-vendors.ce44b678.css" rel="stylesheet"><link href="/css/app.b302f5be.css" rel="stylesheet"><link rel="icon" type="image/png" sizes="32x32" href="/img/icons/favicon-32x32.png"><link rel="icon" type="image/png" sizes="16x16" href="/img/icons/favicon-16x16.png"><link rel="manifest" href="/manifest.json"><meta name="theme-color" content="#4DBA87"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black"><meta name="apple-mobile-web-app-title" content="app"><link rel="apple-touch-icon" href="/img/icons/apple-touch-icon-152x152.png"><link rel="mask-icon" href="/img/icons/safari-pinned-tab.svg" color="#4DBA87"><meta name="msapplication-TileImage" content="/img/icons/msapplication-icon-144x144.png"><meta name="msapplication-TileColor" content="#000000"></head><body><noscript><strong>We're sorry but frontend doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.a9b269ce.js"></script><script src="/js/app.b36ccd51.js"></script></body></html>

Thanks!

**Review by basepi — APPROVED** [review]

**Comment by beniwohli** [comment]
@JBauto can you check if the `SERVER_URL` setting points to your APM Server instance?

    apm = make_apm_client({
        "SERVICE_NAME": "xxx",
        "SERVER_URL": "xxx,  # this should be the URL to your APM Server
        "SERVER_TIMEOUT": "xxx",
        "SECRET_TOKEN": "xxx",
        "DEBUG": True
    })

**Comment by JBauto** [comment]
I think I found the issue. I'm running APM Server behind a proxy and I'm only forward `/intake/*` requests to the APM server. The remaining requests are assumed to be frontend related.

And during the APM initialization, a request is made for the configuration at `/` which goes to the frontend.

https://github.com/elastic/apm-agent-python/blob/d9cf2f26fe323859698c5d5f5ff13c5f9f025adb/elasticapm/transport/http.py#L137-L139

So it's not related to APM but to a misconfiguration on my end.

Sorry and thank you for the help!

**Comment by beniwohli** [comment]
@JBauto awesome, great you were able to figure it out. I'll still merge these changes as they may help other users debug similar issues.

**Pull request merged**
