### PR TITLE
implement support for asyncio [double-plus-WIP]

### PR DESCRIPTION
**Pull request by beniwohli**
DO NOT TRY THIS AT HOME JUST YET

Note: in the v2 API implementation PR, we [removed](https://github.com/elastic/apm-agent-python/pull/281/commits/c2b8d7f1a886) the `AsyncIOHTTPTransport`. It might make sense to re-add it with this PR.

### CODE REVIEW

**Comment by ciarancourtney** [comment]
@beniwohli can you rebase against master when you can, I'd like to test this on twisted

**Comment by beniwohli** [comment]
@ciarancourtney done :) let me know how it goes!

**Comment by ciarancourtney** [comment]
Sorry I misunderstood the PR, I thought it added support for twisted. FYI I'm using `3.0.1` just fine for a twisted/thrift based RPC server using the public API

**Comment by menecio** [comment]
Hi, do you still plan to release this?

**Comment by approxit** [comment]
@menecio I think that this MR is a bit outdated and not closed... Support for asyncio was added in [v4 of apt-agent-python](https://github.com/elastic/apm-agent-python/releases/tag/v4.0.0).

**Comment by beniwohli** [comment]
@approxit unfortunately, that is not quite correct. We did merge some preliminary support for asyncio in 4.0 (like the usage of `contextvars`), but some work still remains to get proper support. I hope to get to this is in the coming few months.

**Comment by beniwohli** [comment]
Closing this, as most parts have been merged or are in the process of being merged in other PRs. Progress on asyncio can be tracked in #598

**Pull request closed without merging**
