### PR TITLE
Fix starlette to not instrument when enabled=False

### PR DESCRIPTION
**Pull request by basepi**
## What does this pull request do?

Noticed that we were gating instrumentation for starlette only on `config.instrument` -- we need to also gate on `config.enabled` to make sure we don't instrument when we shouldn't.

## Related issues
Ref #993

### CODE REVIEW

**Comment by basepi** [comment]
Test failure appears to be a syntax error in pymysql. I'm going to ignore it until this is reviewed/ready to merge, I'm sure they're on it.

**Review by beniwohli — APPROVED** [review]
LGTM! Did you check if it would be feasible to write a test for this?

**Comment by beniwohli** [comment]
pymysql 1.0.1 (and 1.0.2) were released in the meantime, with `python_requires >= 3.6", so tests on 2.7 pass again using a pre 1.0 release.

**Comment by basepi** [comment]
@beniwohli I could probably write a test for this though maybe we should make it a broader issue to write tests for all of our frameworks -- as far as I remember seeing, we're not testing `enabled`/`instrument` in other frameworks either.

**Pull request merged**
