### PR TITLE
Add docs note about setup code in lambda

### PR DESCRIPTION
**Pull request by basepi**
Ref #1711 

Also updated the CHANGELOG for GRPC and disables grpc-1.24 for now to get the nightly tests green.

### CODE REVIEW

**Review by trentm — APPROVED** [review]
LGTM

Is there anything that will track restoring gRPC testing?

**Comment by basepi** [comment]
> Is there anything that will track restoring gRPC testing?

Yep, I planned to make an issue once I saw that the tests did indeed go green, so Beni could look at it when he was back at work.

**Comment by basepi** [comment]
https://github.com/elastic/apm-agent-python/issues/1718

**Pull request merged**
