### PR TITLE
Add support for custom transport json_serializer method

### LINKED ISSUE #1776: Add support for custom transport json_serializer method
**Is your feature request related to a problem? Please describe.**
When I use 
```python
elasticapm.set_custom_context({'message from user': [{'key1': 'value1', 'key2': 'value2'}, {'key1': 'value3', 'key2': 'value4'}, ...]})
```
elastic apm web UI show in metadata my `message from user` something like:
|   |  |
| ------------- | ------------- |
| transaction.custom.message from user.key1  | value1  |
|   | value3 |
|   | ... |
| transaction.custom.message from user.key2  | value2  |
|   | value4 |
|   | ... |

but I expect:
|   |  |
| ------------- | ------------- |
| transaction.custom.message from user | [{'key1': 'value1', 'key2': 'value2'}, {'key1': 'value3, 'key2': 'value4'}, ...]}  |

this is not a problem when len('message from user') is not big, but when it more than 10 it will not good.

**Describe the solution you'd like**
It was great if when I create apm instance via `elasticapm.Client` I can pass parameter like `TRANSPORT_JSON_SERIALIZER` for example and associate it with my custom json serializer that will be used [here](https://github.com/elastic/apm-agent-python/blob/main/elasticapm/transport/base.py#L152).

**Describe alternatives you've considered**
Now it can be solved by cast list object to string representation like:
```python
elasticapm.set_custom_context({'message from user': orjson.dumps([{'key1': 'value1', 'key2': 'value2'}, {'key1': 'value3, 'key2': 'value4'}, ...])})
```
or any other json serialize library like json, simplejson, etc. But in this case I need to add orjson.dumps for every list values that I passed as value in set_custom_context method.

### PR DESCRIPTION
**Pull request by mukhamux**
## What does this pull request do?

Add support for custom transport json_serializer method

## Related issues

Closes #1776

### CODE REVIEW

**Review by basepi — APPROVED** [review]

**Comment by basepi** [comment]
I opened a [PR](https://github.com/mukhamux/apm-agent-python/pull/2) for a lint issue and the changelog. In the future, if you create a new branch instead of using your `main`, I can push directly to your branch for little stuff like that.

Otherwise, this looks great! Looks like your commit was under the email `amukhin@quantumbrains.com` -- make sure you've signed the CLA for that email. Thanks!

**Comment by mukhamux** [comment]
merged

**Comment by basepi** [comment]
@mukhamux you merged `main` from somewhere, but it wasn't in my PR, which is still open: https://github.com/mukhamux/apm-agent-python/pull/2

**Comment by mukhamux** [comment]
merged

**Review by basepi — APPROVED** [review]

**Pull request merged**
