### PR TITLE
Added instrumentation for pymssql

### LINKED ISSUE #239: Instrumentation for PyMSSQL
We use SQLAlchemy heavily and would like to instrument it. Might be able to find time to make an implementation myself if no one beats me to it.

https://pypi.org/project/SQLAlchemy/
http://www.sqlalchemy.org/

### PR DESCRIPTION
**Pull request by beniwohli**
fixes #239

### CODE REVIEW

**Comment by beniwohli** [comment]
@eliasbrange would you mind giving this PR a quick test run? You can install it like so:

    pip install "git+https://github.com/elastic/apm-agent-python.git@refs/pull/241/merge"

**Comment by eliasbrange** [comment]
I tried the instrumentation you wrote by adding to the source directly before which seemed to work. Can try installing the PR tomorrow!

**Comment by eliasbrange** [comment]
Thanks for adding this so quickly. Will make it much easier for me to demo APM.

**Comment by eliasbrange** [comment]
Seems to work good @beniwohli

**Comment by beniwohli** [comment]
Awesome, thanks for testing it! I'll merge this and will do a release in the coming days (waiting for some feedback on the pyodbc instrumentation from another user).

Just as a FYI, we will be dropping support for Python 3.3 in the upcoming release, hope that doesn't affect you.

**Pull request closed without merging**
