### PR TITLE
Add field_name to ConfigurationError messages on init

### PR DESCRIPTION
**Pull request by radupotop**
## What does this pull request do?

Make `ConfigurationError` messages more descriptive on init. This is especially useful where ENV variables are not set.

Turns this error message:

```
ERROR      {/usr/local/lib/python3.10/site-packages/elasticapm/base.py}  is not a float
```
into this:
```
ERROR      {/usr/local/lib/python3.10/site-packages/elasticapm/base.py} TRANSACTION_SAMPLE_RATE= is not a float
```

### CODE REVIEW

**Comment by radupotop** [comment]
Signed CLA

**Comment by xrmx** [comment]
@radupotop thanks for the PR, please run black on it and I'll review

**Review by xrmx — APPROVED** [review]
Thanks for the PR, looks like a nice improvement

**Comment by xrmx** [comment]
run docs-build

**Pull request merged**
