### PR TITLE
Add cgroup support (#831)

### LINKED ISSUE #831: APM Agent on K8s take system memory from host
**Describe the bug**
When using APM agent on Kubernetes cluster, the memory reported in **system.process.memory.size** is incorrect.

To identify this situation whe have the suport of @tanquetav

**To Reproduce**
1. In kibana, search your service metrics:
`service.name : your-service-name and processor.event : metric`
this value is all memory of host.

**Expected behavior**
The correct value of the service.

### LINKED ISSUE #876: Reporting and showing cgroup-based metrics
See https://github.com/elastic/apm/issues/291 for implementation details

### PR DESCRIPTION
**Pull request by tanquetav**
## What does this PR do?
closes #831
closes #876 

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have rebased my changes on top of the latest master branch
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have updated CHANGELOG.asciidoc
- [ ] I have updated supported-technologies.asciidoc
- [ ] Added an API method or config option? Document in which version this will be introduced
- [ ] Added an instrumentation plugin? How did you make sure that old, non-supported versions are not instrumented by accident?
## Use cases
When a java program is running on a cgroup limited environment (docker with -m option, k8s with resource limit) cgroup is used to get memory information(system.memory.total, system.memory.actual.free and system.process.memory.rss)

## Screenshots

### CODE REVIEW

**Comment by beniwohli** [comment]
@tanquetav sorry for letting this linger for so long! I took the liberty to change some variable/method names so they are more aligned with our code style, as well as adding some comments and a few more tests.

I think we can merge this now, what do you think @basepi?

**Review by basepi — APPROVED** [review]
Sounds good to me!

**Comment by tanquetav** [comment]
Let me check it out this weekend. I made some changes on java agent and let me assure the both logic are equals.

**Comment by basepi** [comment]
@tanquetav Did you get a chance to review this again?

**Comment by drnextgis** [comment]
Looking forward to have it being merged :pray:

**Comment by beniwohli** [comment]
I compared the code with the [analogue code](https://github.com/elastic/apm-agent-java/blob/cea4237ed21084241a684b93578e725305630368/apm-agent-core/src/main/java/co/elastic/apm/agent/metrics/builtin/CGroupMetrics.java) in the Java agent, and they seem to be functionally identical. I'll go ahead and merge this.

**Comment by drnextgis** [comment]
The title of the PR is a little bit misleading. Please correct me if I'm wrong but as far as I understood this PR enables memory cgroup-based metrics (which is great!) but we still lack cgroup-based CPU metrics? If so I think it worth to file a separate issue to track the status.

**Comment by beniwohli** [comment]
@drnextgis yes, the PR title doesn't reflect that this just about memory. In the changelog of 5.10.0, we noted that it's only about memory.

Adding CPU metrics is planned, you can follow along here: https://github.com/elastic/apm/issues/368

**Pull request merged**
