### PR TITLE
Tornado framework

### PR DESCRIPTION
**Pull request by laerteallan**
Added integration with tornado framework. 
Added the file "tornado.asciidoc" in docs directory . The file "tornado.ascii" is like the file "flask.asciidoc".

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @laerteallan, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/apm-agent-python/pull/323.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by beniwohli** [comment]
Hi @laerteallan. This is great work! Thank you very much! I hope to have time to take a closer look some time this week.

**Comment by nicholasamorim** [comment]
Hey, any news on this? Can I help somehow?

**Comment by laerteallan** [comment]
> Hey, any news on this? Can I help somehow?

I can. What you need?

**Comment by nicholasamorim** [comment]
Well, help to put the work on it to get this merged to master. I reckon the official version still has no Tornado support, right?

**Comment by laerteallan** [comment]
> Well, help to put the work on it to get this merged to master. I reckon the official version still has no Tornado support, right?
Yes still is'nt. But I'm using this version [tornado_elastic](https://github.com/laerteallan/apm-agent-python-tornado) in my company and of the project that are runing in production.

I  created a package of installation for someone that want to use.

**Comment by basepi** [comment]
@laerteallan We really appreciate the work you did here. I completed a different implementation in #661 and wanted to explain why we went that direction instead of this direction.

We're constantly looking for ways to remove friction from the onboarding experience. Fewer code changes in onboarding make it an easier sell for users. Implementing our own `RequestHandler` subclass as you have is the most obvious way to proceed. Unfortunately, it has two pretty severe drawbacks for onboarding:

1. The user has to replace all instances of `RequestHandler` in their code with our special `APMRequestHandler`, increasing the amount of code change required to use the tool.
2. The functions `on_finish` and `prepare` are designed to be overridden by the user, for any number of purposes. This means the user would also have to remember to call `super()` in order to retain our behavior in those functions.

I was stuck for a long time on how to solve these problems. Then I realized that I could instrument `RequestHandler._execute` instead! It's not as clean as I would like, but it was the only way I could see to maintain an easy onboarding experience. (Really I just wish Tornado had an established middleware or signal mechanism, like Flask and Django 🤦‍♂ )

Anyway, you can see the result of my work in #661. Comments are welcome. And thank you again for the contribution, and our apologies that we weren't able to accept it!

**Pull request closed without merging**
