### PR TITLE
UnicodeDecodeError_starlette_fix

### LINKED ISSUE #1556: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 369: invalid start byte
**Describe the bug**: 
Sending PUT request to FastAPI with binary file encoded, its returns a error.

**To Reproduce**

1. Configure FastAPI with elasticapm.contrib.starlette
2. Send a PUT request with binary file

**Environment (please complete the following information)**
- OS: Linux
- Python version: 3.8
- Framework and version: fastapi 0.61.2
- APM Server version: 8
- Agent version: 8

The same problema was resolved in the main code : [#344](https://github.com/elastic/apm-agent-python/issues/334)

### PR DESCRIPTION
**Pull request by silici0**
## What does this pull request do?

Fix on error when try to decode body thats was send with a binary file

Related to problem with other commit #1557 

## Related issues
closes #1556

### CODE REVIEW

**Review by basepi — APPROVED** [review]

**Comment by silici0** [comment]
Let me know if i need to do any more actions. Thanks

**Review by beniwohli — APPROVED** [review]
Good catch, thanks for opening the PR!

**Pull request merged**
