### PR TITLE
Force pulling latest docker image for python version.

### PR DESCRIPTION
**Pull request by simitt**

### CODE REVIEW

**Comment by simitt** [comment]
@beniwohli I removed the versioning for installing `flake8` and `isort` so that also jenkins will download the latest version in the future.

**Comment by beniwohli** [comment]
@simitt can you rebase on master?

**Comment by simitt** [comment]
@beniwohli done 
The tests now fail with this update as you already pointed out - I leave the fixes up to you.

**Comment by beniwohli** [comment]
@simitt they shouldn't fail, master has the fixes from #81 applied. Guess we'll find out :D

**Comment by simitt** [comment]
ah great, I missed that

**Pull request merged**
