### PR TITLE
added instrumentation for mysql-connector and pymysql

### PR DESCRIPTION
**Pull request by beniwohli**

### CODE REVIEW

**Comment by holdenrehg** [comment]
Very excited and in need of this one :+1:

**Comment by beniwohli** [comment]
@holdenrehg this has now been released in version 5.3.0 of the agent. Would love to hear if it works for you!

**Comment by holdenrehg** [comment]
> @holdenrehg this has now been released in version 5.3.0 of the agent. Would love to hear if it works for you!

Awesome. I'll give it a test this week and let you know!

**Comment by holdenrehg** [comment]
@beniwohli works just as expected for me now after bumping up to the latest version (`5.3.1`)

For context, I'm using Flask and `mysqlconnector` with SQLAlchemy.

```python
"SQLALCHEMY_DATABASE_URI": "mysql+mysqlconnector://{username}:{password}@{host}:{port}/{database}"
```
November-22-2019-12-13-42

**Pull request merged**
