### PR TITLE
Doesn"t cut request body with size >= 10000

### PR DESCRIPTION
**Pull request by mukhamux**
## What does this pull request do?
b4edea3ca7885f5cbbad202a8f12325d131225ce has errors, if body size has more than 10000 bytes, it writes 10000 bytes message to elastic and call await self.app(scope, receive, wrapped_send) with same receive and invalid body, 

## Comment:
I separate receivers and now, if request has body more than 10000 bytes -> it will send to elastic only 10000 bytes and continue handle as normal request without cutting

### CODE REVIEW

**Comment by mukhamux** [comment]
Find strange bug in API realted with apm agent is more easier than make a pull request...

**Comment by mukhamux** [comment]
run elasticsearch-ci/docs

**Comment by basepi** [comment]
Sorry for the confusion, but only people with write access to the repo can trigger the tests. I'll take a look at this today.

**Review by basepi — APPROVED** [review]
Wow this definitely was broken, thank you for the catch and the fix! 😅

**Comment by basepi** [comment]
I opened a PR to add a CHANGELOG entry and fix the test to test this: https://github.com/mukhamux/apm-agent-python/pull/1

**Comment by mukhamux** [comment]
> I opened a PR to add a CHANGELOG entry and fix the test: [mukhamux#1](https://github.com/mukhamux/apm-agent-python/pull/1)

merged

**Pull request merged**
