### PR TITLE
Add public API to retrieve trace parent header.

### PR DESCRIPTION
**Pull request by diegosperes**
## What does this pull request do?

Add a new public API to easily return the trace parent header of the current transaction, currently it's necessary to dig into the project and understand how it works.

Code necessary to get the current trace parent header without the new function.

```
from elasticapm.traces import execution_context

transaction = execution_context.get_transaction().
trace_parent_header = transaction .trace_parent.to_string() if transaction and transaction.trace_parent else None
```

## Related issues

https://github.com/elastic/apm-agent-python/issues/954

### CODE REVIEW

**Comment by diegosperes** [comment]
Couldn't find which place should I add the unit test, does someone has any suggestion? I think there isn't a test case for public API.

**Comment by beniwohli** [comment]
Hey @diegosperes. This looks like a nice addition to the public API! You're right, the testing for public APIs isn't very extensive, but there are a few here that might serve as inspiration: 

https://github.com/elastic/apm-agent-python/blob/65e8b7c7becd85476dda5870781042eab2e2e2ac/tests/instrumentation/transactions_store_tests.py#L363-L442

It would also be great if you could add an entry in the traceparent docs here: https://github.com/elastic/apm-agent-python/blob/master/docs/api.asciidoc#traceparent.

**Comment by diegosperes** [comment]
@beniwohli thanks for guide me, I added a few missing test for the public API also a new entry for this function in the traceparent docs.

**Review by beniwohli — APPROVED** [review]
This is great work, thanks a lot!

@basepi ok with merging this?

**Review by basepi — APPROVED** [review]

**Pull request merged**
