### PR TITLE
WIP: feat: add sanic support for elastic-apm python agent

### PR DESCRIPTION
**Pull request by harshanarayana**
### Description
This PR is a quick prototype of what it would look like when it comes to enabling the elastic APM client support for `sanic`.

Closes elastic/apm-agent-python#521 

### To Do
- [ ] Update Tests
- [ ] Update Documentation
- [ ] Add example usage

### CODE REVIEW

**Comment by dadoeyad** [comment]
Any updates on this PR? :D

**Comment by basepi** [comment]
As referenced in #521, there were some issues with blocking code potentially causing issues in sanic. As far as I can tell, most of those have been fixed. Source code collection is now in a background thread as of #607.

I think we can probably move forward on this, if @harshanarayana is willing and able. We added support for a couple of async frameworks recently as well, for reference: [tornado](https://github.com/elastic/apm-agent-python/pull/661), [starlette](https://github.com/elastic/apm-agent-python/pull/694), and [aiohttp](https://github.com/elastic/apm-agent-python/pull/659)

**Comment by harshanarayana** [comment]
@dadoeyad Time for me to resurrect this PR and get this one sorted. I will take some time and get this one done over the weekend. 

@basepi I will take a look at the way the support has been added to the other frameworks and see how much of it can be leveraged into sanic. I will push the changes to this PR shortly

**Comment by ajay1mg** [comment]
Is there any development on this? Any plans on adding native support for Sanic. This framework also is getting some serious attention

**Comment by alexcc4** [comment]
Is there any development on this?

**Comment by basepi** [comment]
@alexcc4 The latest version is in #1056 -- I think it's close to being finished.

**Comment by alexcc4** [comment]
awesome!

**Pull request closed without merging**
