### PR TITLE
Feature/git 521 sanic apm contrib

### LINKED ISSUE #521: Proposal: Enable support for Sanic
**Is your feature request related to a problem? Please describe.**
This feature proposal describes the request to include support for [`sanic`](https://github.com/huge-success/sanic ) framework.

Sanic is being adopted widely by a large developer community and like `Flask` there is a need to add support for `Sanic` under the Elastic APM python client. 

**Describe the solution you'd like**
Add sanic support under contrib

**Describe alternatives you've considered**
I've a personal project going for supporting opentracing spec using Jaeger Client for Sanic but there is nothing available for sanic under the elastic-apm umbrella.

**Additional context**
NA

### PR DESCRIPTION
**Pull request by ahopkins**
## What does this pull request do?

Is a cleanup of @harshanarayana PR (https://github.com/elastic/apm-agent-python/pull/1056) to add compat with Sanic v21.9

## Related issues
closes #521

### CODE REVIEW

**Comment by basepi** [comment]
@ahopkins Can you sign [the CLA](https://www.elastic.co/contributor-agreement) please?

**Comment by ahopkins** [comment]
> @ahopkins Can you sign [the CLA](https://www.elastic.co/contributor-agreement) please?

I did :unamused:

**Comment by ajaygupta2790** [comment]
> This branch is out-of-date with the base branch
@ahopkins you need to sync with base branch, there was a release an hour ago

**Comment by ahopkins** [comment]
> > This branch is out-of-date with the base branch
> > @ahopkins you need to sync with base branch, there was a release an hour ago

I was waiting to see if the `elasticsearch-ci/docs` would succeed or not.

**Comment by ahopkins** [comment]
:cry: broken tests

**Comment by ahopkins** [comment]
@ajaygupta2790 @basepi I am not sure what to make of that failure. Please LMK.

**Comment by ajaygupta2790** [comment]
> 😢 broken tests

I built this PR on my local and all test cases passed for sanic and python 3.7. @basepi need your support here.

**Comment by basepi** [comment]
Sorry, sometimes the CLA takes a bit to show up. It's showing green now so we're good! Once the tests run again I'll look at any failures that remain.

**Comment by basepi** [comment]
run elasticsearch-ci/docs

**Comment by basepi** [comment]
run elasticsearch-ci/docs

**Pull request merged**
