### PR TITLE
Fix on UnicodeDecodeError on FastAPI plugin

### PR DESCRIPTION
**Pull request by silici0**
## What does this pull request do?
Fix on error when try to decode body thats was send with a binary file

## Related issues
closes #[1556](https://github.com/elastic/apm-agent-python/issues/1556)

### CODE REVIEW

**Review by basepi — APPROVED** [review]

**Comment by silici0** [comment]
> This looks awesome, thank you! Did you get a chance to sign [the CLA](https://www.elastic.co/contributor-agreement)?

I have signed : 
image

But its doesnt work! I missing something

**Comment by basepi** [comment]
I think it probably is fine but the CLA checker is just being slow. Thanks!

**Comment by basepi** [comment]
I think I spotted the problem. Your local git environment doesn't have an email configured:

```
# git show 2f0fe2a2d6b59d73fb7dec418d151943dfadd434
commit 2f0fe2a2d6b59d73fb7dec418d151943dfadd434
Author: Rafael Cunha <silici0@Rafaels-MacBook-Pro.local>
Date:   Mon May 23 16:35:36 2022 -0300
```

Note the `silici0@Rafaels-MacBook-Pro.local` in the author line. Thus the CLA tool isn't matching your commit.

You'll want to do this:

```bash
git config --global user.email "email@example.com"
```

And then either force a rebase or re-commit your change. The latter is the easiest:

```bash
git reset --hard upstream/main
git cherry-pick 2f0fe2a2d6b59d73fb7dec418d151943dfadd434
git push -f origin UnicodeDecodeError_starlette
```

**Comment by silici0** [comment]
> I think I spotted the problem. Your local git environment doesn't have an email configured:
> 
> ```
> # git show 2f0fe2a2d6b59d73fb7dec418d151943dfadd434
> commit 2f0fe2a2d6b59d73fb7dec418d151943dfadd434
> Author: Rafael Cunha <silici0@Rafaels-MacBook-Pro.local>
> Date:   Mon May 23 16:35:36 2022 -0300
> ```
> 
> Note the `silici0@Rafaels-MacBook-Pro.local` in the author line. Thus the CLA tool isn't matching your commit.
> 
> You'll want to do this:
> 
> ```shell
> git config --global user.email "email@example.com"
> ```
> 
> And then either force a rebase or re-commit your change. The latter is the easiest:
> 
> ```shell
> git reset --hard upstream/main
> git cherry-pick 2f0fe2a2d6b59d73fb7dec418d151943dfadd434
> git push -f origin UnicodeDecodeError_starlette
> ```
> 
> More info [here.](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git)

Thanks very much! You are awesome! 

/test

**Comment by basepi** [comment]
Unfortunately it still didn't work:

```
# git show
commit bd07b5142be3695bd5c8df545761441bcf0f614d (HEAD -> UnicodeDecodeError_starlette)
Author: Rafael Cunha <silici0@Rafaels-MacBook-Pro.local>
```

It's possible you have that `silici0@Rafaels-MacBook-Pro.local` configured in your `.git/config` so it's overriding your global setting. I'm not sure.

Try again, but before you do the `git push -f`, use `git show` to check that your email is correct.

**Comment by basepi** [comment]
(It's also possible that `git cherry-pick` doesn't update the email. You may just have to make the commit fresh)

**Pull request closed without merging**
