### PR TITLE
refactor httpx instrumentation

### LINKED ISSUE #1399: Flaky Test [Initializing / Test / Python-pypy-3-2 / test_httpx_instrumentation – tests.instrumentation.httpx_tests]
## Flaky Test

* **Test Name:** `Initializing / Test / Python-pypy-3-2 / test_httpx_instrumentation – tests.instrumentation.httpx_tests`
* **Artifact Link:** https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1398/detail/PR-1398/2/
* **PR:** #1398
* **Commit:** f06362c100e04242a931bce20b8ad43fdf6f7db1

### Error details
```
AssertionError: assert "traceparent" in EnvironHeaders([("Host", "127.0.0.1:39855"), ("Accept", "*/*"), ("Accept-Encoding", "gzip, deflate"), ("Connection", "keep-alive"), ("User-Agent", "python-httpx/0.21.0")])
 +  where "traceparent" = constants.TRACEPARENT_HEADER_NAME
```

### Stack Trace
```
instrument = None
elasticapm_client = <tests.fixtures.TempStoreClient object at 0x000000000bb860c8>
waiting_httpserver = <ContentServer(<class "pytest_localserver.http.ContentServer">, started 140399483520768)>

    def test_httpx_instrumentation(instrument, elasticapm_client, waiting_httpserver):
        waiting_httpserver.serve_content("")
        url = waiting_httpserver.url + "/hello_world"
        parsed_url = compat.urlparse.urlparse(url)
        elasticapm_client.begin_transaction("transaction.test")
        with capture_span("test_request", "test"):
            httpx.get(url, **allow_redirects)
        elasticapm_client.end_transaction("MyView")
    
        transactions = elasticapm_client.events[TRANSACTION]
        spans = elasticapm_client.spans_for_transaction(transactions[0])
        assert spans[0]["name"].startswith("GET 127.0.0.1:")
        assert spans[0]["type"] == "external"
        assert spans[0]["subtype"] == "http"
        assert url == spans[0]["context"]["http"]["url"]
        assert spans[0]["context"]["destination"]["service"] == {
            "name": "",
            "resource": "127.0.0.1:%d" % parsed_url.port,
            "type": "",
        }
    
        headers = waiting_httpserver.requests[0].headers
>       assert constants.TRACEPARENT_HEADER_NAME in headers
E       AssertionError: assert "traceparent" in EnvironHeaders([("Host", "127.0.0.1:39855"), ("Accept", "*/*"), ("Accept-Encoding", "gzip, deflate"), ("Connection", "keep-alive"), ("User-Agent", "python-httpx/0.21.0")])
E        +  where "traceparent" = constants.TRACEPARENT_HEADER_NAME

tests/instrumentation/httpx_tests.py:73: AssertionError
```

### LINKED ISSUE #1400: Flaky Test [Initializing / Test / Python-pypy-3-2 / test_httpx_instrumentation_via_client – tests.instrumentation.httpx_tests]
## Flaky Test

* **Test Name:** `Initializing / Test / Python-pypy-3-2 / test_httpx_instrumentation_via_client – tests.instrumentation.httpx_tests`
* **Artifact Link:** https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-1398/detail/PR-1398/2/
* **PR:** #1398
* **Commit:** f06362c100e04242a931bce20b8ad43fdf6f7db1

### Error details
```
AssertionError: assert "traceparent" in EnvironHeaders([("Host", "127.0.0.1:33671"), ("Accept", "*/*"), ("Accept-Encoding", "gzip, deflate"), ("Connection", "keep-alive"), ("User-Agent", "python-httpx/0.21.0")])
 +  where "traceparent" = constants.TRACEPARENT_HEADER_NAME
```

### Stack Trace
```
instrument = None
elasticapm_client = <tests.fixtures.TempStoreClient object at 0x000000000308e368>
waiting_httpserver = <ContentServer(<class "pytest_localserver.http.ContentServer">, started 140399483520768)>

    def test_httpx_instrumentation_via_client(instrument, elasticapm_client, waiting_httpserver):
        waiting_httpserver.serve_content("")
        url = waiting_httpserver.url + "/hello_world"
        elasticapm_client.begin_transaction("transaction.test")
        with capture_span("test_request", "test"):
            c = httpx.Client()
            c.get(url, **allow_redirects)
        elasticapm_client.end_transaction("MyView")
    
        transactions = elasticapm_client.events[TRANSACTION]
        spans = elasticapm_client.spans_for_transaction(transactions[0])
        assert spans[0]["name"].startswith("GET 127.0.0.1:")
        assert url == spans[0]["context"]["http"]["url"]
    
        headers = waiting_httpserver.requests[0].headers
>       assert constants.TRACEPARENT_HEADER_NAME in headers
E       AssertionError: assert "traceparent" in EnvironHeaders([("Host", "127.0.0.1:33671"), ("Accept", "*/*"), ("Accept-Encoding", "gzip, deflate"), ("Connection", "keep-alive"), ("User-Agent", "python-httpx/0.21.0")])
E        +  where "traceparent" = constants.TRACEPARENT_HEADER_NAME

tests/instrumentation/httpx_tests.py:101: AssertionError
```

### LINKED ISSUE #1401: Flaky Test [Initializing / Test / Python-pypy-3-2 / test_httpx_instrumentation_via_client – tests.instrumentation.httpx_tests]
## Flaky Test

* **Test Name:** `Initializing / Test / Python-pypy-3-2 / test_httpx_instrumentation_via_client – tests.instrumentation.httpx_tests`
* **Artifact Link:** https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-python%2Fapm-agent-python-mbp%2FPR-705/detail/PR-705/116/
* **PR:** #705
* **Commit:** e2e7239aee243c8f0c6fecf650d39f1f493be6b3

### Error details
```
AssertionError: assert "traceparent" in EnvironHeaders([("Host", "127.0.0.1:38837"), ("Accept", "*/*"), ("Accept-Encoding", "gzip, deflate"), ("Connection", "keep-alive"), ("User-Agent", "python-httpx/0.21.0")])
 +  where "traceparent" = constants.TRACEPARENT_HEADER_NAME
```

### Stack Trace
```
instrument = None
elasticapm_client = <tests.fixtures.TempStoreClient object at 0x0000000006a27d70>
waiting_httpserver = <ContentServer(<class "pytest_localserver.http.ContentServer">, started 139883109521152)>

    def test_httpx_instrumentation_via_client(instrument, elasticapm_client, waiting_httpserver):
        waiting_httpserver.serve_content("")
        url = waiting_httpserver.url + "/hello_world"
        elasticapm_client.begin_transaction("transaction.test")
        with capture_span("test_request", "test"):
            c = httpx.Client()
            c.get(url, **allow_redirects)
        elasticapm_client.end_transaction("MyView")
    
        transactions = elasticapm_client.events[TRANSACTION]
        spans = elasticapm_client.spans_for_transaction(transactions[0])
        assert spans[0]["name"].startswith("GET 127.0.0.1:")
        assert url == spans[0]["context"]["http"]["url"]
    
        headers = waiting_httpserver.requests[0].headers
>       assert constants.TRACEPARENT_HEADER_NAME in headers
E       AssertionError: assert "traceparent" in EnvironHeaders([("Host", "127.0.0.1:38837"), ("Accept", "*/*"), ("Accept-Encoding", "gzip, deflate"), ("Connection", "keep-alive"), ("User-Agent", "python-httpx/0.21.0")])
E        +  where "traceparent" = constants.TRACEPARENT_HEADER_NAME

tests/instrumentation/httpx_tests.py:101: AssertionError
```

### PR DESCRIPTION
**Pull request by beniwohli**
httpx 0.21 and httpcore 0.14 once again changed how it works,
necessitating more special handling. To make this a tad less
cumbersome, most of this code has moved into a utils file.
To make the structure somewhat sane, httpx got its own
package in instrumentation.

closes #1399
closes #1400
closes #1401

### CODE REVIEW

**Comment by beniwohli** [comment]
full test matrix was built with the exception of some Python 3.8 runs which were aborted for some reason. It passed for all other CPython versions, so the abort was probably unrelated.

**Review by basepi — APPROVED** [review]
Good simplification in addition to fixing compat. :+1:

**Pull request merged**
