### PR TITLE
Upgrade coverage and pytest-cov

### PR DESCRIPTION
**Pull request by basepi**
## What does this pull request do?

Upgrades `coverage` and `pytest-cov` in the test suite. Trying to nail down any easy fixes for the py3.12 segfault that I've been avoiding digging into.

### CODE REVIEW

**Comment by trentm** [comment]
Had to go spelunking to find the drop of Python 3.6 support: https://github.com/pytest-dev/pytest-cov/compare/v4.0.0...v4.1.0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L114

**Review by trentm — DISMISSED** [review]
Wassup with this Windows Py3.7 failure? https://github.com/elastic/apm-agent-python/actions/runs/6331462880/job/17196073071?pr=1906

**Comment by basepi** [comment]
No clue. I'll look more tomorrow.

**Comment by basepi** [comment]
I went ahead and removed python3.7 testing on windows, since it's EOL anyway.

I really want to remove our windows support altogether. I've never met a single windows user of the agent, and it's been nothing but false positives and flaky tests in the CI. Unfortunately, we don't have host os data in `apm-per-service`, so it's hard to verify user numbers.

**Review by trentm — APPROVED** [review]

**Pull request merged**
